# Generated by Django 4.0.1 on 2022-04-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_scholarship', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extenduser',
            old_name='profilepic',
            new_name='picture',
        ),
    ]
