# Generated by Django 4.0.1 on 2022-04-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='extention',
            field=models.CharField(default='', max_length=100),
        ),
    ]
