# Generated by Django 4.0.1 on 2022-06-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_scholarship', '0002_alter_extenduser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='cellphone',
            field=models.BigIntegerField(default='', null=True),
        ),
    ]
