# Generated by Django 4.0.1 on 2022-04-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_scholarship', '0003_alter_extenduser_extention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='religion',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
