# Generated by Django 4.0.1 on 2022-06-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_scholarship', '0003_alter_extenduser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='gcontact',
            field=models.CharField(default='+63 ', max_length=100, null=True),
        ),
    ]
