# Generated by Django 4.0.1 on 2022-06-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_scholarship', '0003_alter_extenduser_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='cellphone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='fcontact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='gcontact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='mcontact',
            field=models.BigIntegerField(null=True),
        ),
    ]
