# Generated by Django 4.0.1 on 2022-06-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_scholarship', '0004_alter_extenduser_gcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='cellphone',
            field=models.CharField(default='+63 ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='fcontact',
            field=models.CharField(default='+63 ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='mcontact',
            field=models.CharField(default='+63 ', max_length=100, null=True),
        ),
    ]
