# Generated by Django 4.0.1 on 2022-04-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_scholarship', '0004_alter_extenduser_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='cellphone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='fcontact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='gcontact',
            field=models.BigIntegerField(null=True),
        ),
    ]
