# Generated by Django 4.0.1 on 2022-06-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_scholarship', '0004_alter_extenduser_age_alter_extenduser_cellphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
    ]
