# Generated by Django 4.0.1 on 2022-04-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_scholarship', '0005_alter_extenduser_cellphone_alter_extenduser_fcontact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='mcontact',
            field=models.BigIntegerField(null=True),
        ),
    ]
