# Generated by Django 4.0.1 on 2022-04-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_scholarship', '0006_alter_extenduser_mcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
